sudo: required
services:
  - docker

before_install:
  - docker build -t HaraldPaterek/react-test -f ./client/Dockerfile.dev

script:
  - docker run HaraldPaterek/react-test npm test -- --coverage

after_success:
  - docker build -t HaraldPaterek/multi-nginx ./nginx
  - docker build -t HaraldPaterek/multi-server ./server
  - docker build -t HaraldPaterek/multi-client ./client
  - docker build -t HaraldPaterek/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push the images to docker hub
  - docker push HaraldPaterek/multi-nginx 
  - docker push HaraldPaterek/multi-server
  - docker push HaraldPaterek/multi-client
  - docker push HaraldPaterek/multi-worker 